name: taski
description: A challenge mobile application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  device_preview: ^1.2.0
  either_dart: ^1.0.0
  equatable: ^2.0.7
  firebase_core: ^3.9.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.16
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  mocktail: ^1.0.4
  path: ^1.9.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  sqflite: ^2.4.1
  sqflite_common_ffi_web: ^0.4.5+4

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/imgs/
    - assets/svgs/
